dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  pigment: null
  shimmer: null
  transparent_image: null
description: A new Flutter project.
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.1.0 <3.0.0"
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-100.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-100italic.ttf
          style: italic
          weight: 100
        - asset: fonts/Montserrat/Montserrat-200.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-200italic.ttf
          style: italic
          weight: 200
        - asset: fonts/Montserrat/Montserrat-300.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-300italic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat/Montserrat-regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Montserrat/Montserrat-500.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-500italic.ttf
          style: italic
          weight: 500
        - asset: fonts/Montserrat/Montserrat-600.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-600italic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat/Montserrat-700.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-700italic.ttf
          style: italic
          weight: 700
        - asset: fonts/Montserrat/Montserrat-800.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-800italic.ttf
          style: italic
          weight: 800
        - asset: fonts/Montserrat/Montserrat-900.ttf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-900italic.ttf
          style: italic
          weight: 900
  uses-material-design: true
name: endemica
version: 1.0.0+1
